## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'avantes'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_template become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_avantes' #to modify
description = 'Set of plugins for the Avantes spectrometers'

author = 'Sébastien Weber'
author-email = 'sebastien.weber@cemes.fr'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = []
